// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB802hk5iAFsvDkDuZX_IR3bybBt2nGQ1w',
    appId: '1:164865792387:web:0cd883b1e9077f9a513eb6',
    messagingSenderId: '164865792387',
    projectId: 'thinkerview-flutter',
    authDomain: 'thinkerview-flutter.firebaseapp.com',
    storageBucket: 'thinkerview-flutter.appspot.com',
    measurementId: 'G-WLCDS0FPTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFX9aI8dSPHQUqdgLQVlp4HUfToXFQh1Q',
    appId: '1:164865792387:android:19b69c55c9115830513eb6',
    messagingSenderId: '164865792387',
    projectId: 'thinkerview-flutter',
    storageBucket: 'thinkerview-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSOjH_7-UMphMFTQ7umpFdNayf5dgupCY',
    appId: '1:164865792387:ios:c99834d9019f835b513eb6',
    messagingSenderId: '164865792387',
    projectId: 'thinkerview-flutter',
    storageBucket: 'thinkerview-flutter.appspot.com',
    iosClientId:
        '164865792387-jprdul27dcoe13qj77hdei0htsjbnubm.apps.googleusercontent.com',
    iosBundleId: 'com.thinkerview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSOjH_7-UMphMFTQ7umpFdNayf5dgupCY',
    appId: '1:164865792387:ios:c99834d9019f835b513eb6',
    messagingSenderId: '164865792387',
    projectId: 'thinkerview-flutter',
    storageBucket: 'thinkerview-flutter.appspot.com',
    iosClientId:
        '164865792387-jprdul27dcoe13qj77hdei0htsjbnubm.apps.googleusercontent.com',
    iosBundleId: 'com.thinkerview',
  );
}
