// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNsw6xO8w-e0SCELMAN9p2UCIxQmCj4yY',
    appId: '1:297571903377:web:467c285fe10cd61d555c30',
    messagingSenderId: '297571903377',
    projectId: 'cause-commune-flutter',
    authDomain: 'cause-commune-flutter.firebaseapp.com',
    storageBucket: 'cause-commune-flutter.appspot.com',
    measurementId: 'G-WVEE36TEPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cUXAWEt0vGckRhX1Pb1lkw8brMcmFYk',
    appId: '1:297571903377:android:1747ea74fbabe7c5555c30',
    messagingSenderId: '297571903377',
    projectId: 'cause-commune-flutter',
    storageBucket: 'cause-commune-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB48rxJGzhRFlvDostAkw1uGb_M2s86OZM',
    appId: '1:297571903377:ios:c8c9bc77fe5decd0555c30',
    messagingSenderId: '297571903377',
    projectId: 'cause-commune-flutter',
    storageBucket: 'cause-commune-flutter.appspot.com',
    iosClientId:
        '297571903377-1v02bn65lm232e25e7kod5qehe6kmhvf.apps.googleusercontent.com',
    iosBundleId: 'com.cause.commune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB48rxJGzhRFlvDostAkw1uGb_M2s86OZM',
    appId: '1:297571903377:ios:c8c9bc77fe5decd0555c30',
    messagingSenderId: '297571903377',
    projectId: 'cause-commune-flutter',
    storageBucket: 'cause-commune-flutter.appspot.com',
    iosClientId:
        '297571903377-1v02bn65lm232e25e7kod5qehe6kmhvf.apps.googleusercontent.com',
    iosBundleId: 'com.cause.commune',
  );
}
